name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18

      - name: Install npm deps
        run: pnpm ci

      - name: Dependency check
        run: pnpm run depcheck
